// Package springconfig turns resolved cluster env into laptop-side config a Spring
// Boot app boots from unchanged. The primary form is an env-file: Spring Boot's
// relaxed binding lets environment variables override application.yaml/properties,
// so SPRING_DATASOURCE_URL=... wins over spring.datasource.url in YAML with no app
// changes and regardless of whether the app uses YAML or properties.
package springconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/hzeng10/local-debug/internal/k8s"
)

// WriteEnvFile writes vars as KEY=VALUE lines (Telepresence --env-file / IDE EnvFile
// format) to path, creating parent dirs. Skipped vars are emitted as comments so the
// developer can see what was intentionally not reproduced. Returns the counts.
func WriteEnvFile(path string, vars []k8s.EnvVar) (written, skipped int, err error) {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return 0, 0, fmt.Errorf("create dir %q: %w", dir, err)
		}
	}
	var b strings.Builder
	b.WriteString("# Generated by ldbg — cluster env for local debugging. Do not commit (may contain secrets).\n")
	for _, v := range vars {
		if v.Skipped {
			skipped++
			fmt.Fprintf(&b, "# %s skipped: %s\n", v.Name, v.Reason)
			continue
		}
		if v.Source == k8s.SourceSynthetic {
			fmt.Fprintf(&b, "# %s is synthetic — injected by ldbg (not from the cluster); Spring Boot relaxed binding maps it to logging.file.name. Opt out with --no-local-log.\n", v.Name)
		}
		fmt.Fprintf(&b, "%s=%s\n", v.Name, escapeValue(v.Value))
		written++
	}
	// 0600: the file may contain secret values.
	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return 0, 0, fmt.Errorf("write env-file %q: %w", path, err)
	}
	return written, skipped, nil
}

// escapeValue keeps multi-line / special values usable in env-file form by collapsing
// newlines (Telepresence env-files are line-oriented). Single-line values pass through.
func escapeValue(v string) string {
	if !strings.ContainsAny(v, "\n\r") {
		return v
	}
	return strings.NewReplacer("\r", "", "\n", "\\n").Replace(v)
}

// LoadEnvFile parses an env-file (KEY=VALUE lines, # comments) back into a slice of
// "KEY=VALUE" strings suitable for exec.Cmd.Env, reversing escapeValue's newline
// collapsing. Used by `up --run` to launch the local app with the synced env.
func LoadEnvFile(path string) ([]string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var env []string
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		v = strings.ReplaceAll(v, "\\n", "\n")
		env = append(env, k+"="+v)
	}
	return env, nil
}

// Summarize returns a deterministic, secret-masked one-line-per-var view for display.
// maskFn is injected (internal/output.Mask) to avoid a dependency cycle.
func Summarize(vars []k8s.EnvVar, maskFn func(string) string) []string {
	lines := make([]string, 0, len(vars))
	for _, v := range vars {
		switch {
		case v.Skipped:
			lines = append(lines, fmt.Sprintf("  ~ %-32s (skipped: %s)", v.Name, v.Reason))
		case v.Secret:
			lines = append(lines, fmt.Sprintf("  • %-32s = %s   [%s]", v.Name, maskFn(v.Value), v.Source))
		default:
			lines = append(lines, fmt.Sprintf("  • %-32s = %s   [%s]", v.Name, v.Value, v.Source))
		}
	}
	sort.Strings(lines)
	return lines
}
